### ISSUE TITLE
请问一下telegram bot推送还能正常使用吗

### ISSUE THREAD

**Issue by kpzhao** [panghaibin/shuasr#7]
我的填报正常，但是tg没有推送了，有用tg推送的小伙伴吗

**Comment by panghaibin** [comment]
tg bot 推送不能使用是因为现在是全局连接了学校VPN再运行的程序，这个问题有待解决

**Comment by kpzhao** [comment]
> tg bot 推送不能使用是因为现在是全局连接了学校VPN再运行的程序，这个问题有待解决

搜嘎，那我换成其他推送吧，谢谢大佬
