### ISSUE TITLE
在沪不在校情况出现填报错误

### ISSUE THREAD

**Issue by TanFang98** [panghaibin/shuasr#8]
3月21日返家以后手动填报了一次，但是今天开始一直填报错误
日志如下：
 {'__EVENTTARGET': 'p1$ctl01$btnSubmit', 'p1$pnlDangSZS$DangSZS': ['A'], 'p1$BaoSRQ': '2022-03-22', 'p1$ShiFSH': '在上海（不在校内）', 'p1$ShiFZX': '否', 'p1$ShiFZJ': '是', 'F_TARGET': 'p1_ctl01_btnSubmit', 'p1$ddlSheng$Value': '***海, length: 2', 'p1$ddlSheng': '***海, length: 2', 'p1$ddlShi$Value': '***市, length: 3', 'p1$ddlShi': '***市, length: 3', 'p1$ddlXian$Value': '***区, length: 3', 'p1$ddlXian': '***区, length: 3', 'p1$XiangXDZ': '***室, length: 14', 'p1$pImages$HFimgSuiSM': '***=, length: 12', 'p1$pImages$HFimgXingCM': '***=, length: 12'}

**Comment by panghaibin** [comment]
程序更新到最新就可以了

可以考虑安装 Pull App https://github.com/apps/pull ，应用到对应仓库，保持fork为最新
